### ISSUE TITLE
Use with sib-pair data

### ISSUE THREAD

**Issue by jlc-christie** [gusevlab/germline#2]
Hi, 

The paper this was released under (Whole population, genome-wide mapping of hidden relatedness) implies that this is intended for finding the extend of relatedness between seemingly unrelated individuals. But is the performance on germline known for familial data (e.g. sib-pairs)? I'm currently using [Merlin](http://csg.sph.umich.edu/abecasis/merlin/) to get marker-level IBD status, but the input/output format is very dated, and the speed isn't great either. Does germline account for known pedigrees? 

Thanks,
James

**Comment by sashagusev** [comment]
Hi James, GERMLINE does not explicitly model pedigree structure (i.e. it treats related individuals as if they were completely independent in the analysis) but if you have dense SNP data GERMLINE should still be very accurate on this type of data. If you're using sparse/old-gen SNP data I would still recommend using something model-based like MERLIN because it can use the known structure but otherwise GERMLINE should be fine.

You can also look into method that post-process GERMLINE data to recover the pedigree relationships (e.g. ERSA https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5586387/) and benchmark accuracy that way.

**Comment by jlc-christie** [comment]
Thanks for the detailed reply! :)
